### ISSUE TITLE
Neat.evolve() does not have a default fitness function

### ISSUE THREAD

**Issue by luiscarbonell** [liquidcarrot/carrot#72]
### Describe the bug

The following throws an error - it should not, ideally.

**Code**
```javascript
const { Neat } = require("@liquid-carrot/carrot");

...

let pop = new Neat(10, 5);
pop.evolve(data);
```

**Error**
```
(node:6876) UnhandledPromiseRejectionWarning: Error: You must include a dataset to use NEAT.evaluate()
    at Neat.evaluate (/home/luiscarbonell5683/workspace/carrot/src/neat.js:297:13)
    at Neat.evolve (/home/luiscarbonell5683/workspace/carrot/src/neat.js:192:94)
    at /home/luiscarbonell5683/workspace/carrot/sandbox/trading.js:97:15
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### To Reproduce

* Node.js v10.15.3

### Expected behavior

* No error
* A new `Network` with an improved topology and weights

**Comment by christianechevarria** [comment]
Resolved by https://github.com/liquidcarrot/carrot/pull/82
